import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API=import.meta.env.VITE_API_URL || 'http://localhost:8000';
type AnyData=Record<string,any>;
const initial={name:'Loyalty upgrade',request:'Find customers likely to upgrade',purpose:'personalized_advertising',channel:'display',destination:'mock-dsp',max_audience:100};

function App(){
 const [config,setConfig]=useState<AnyData>({mode:'loading',scenarios:{},sandboxes:{}}),[brief,setBrief]=useState(initial),[scenario,setScenario]=useState('authorized_success');
 const [result,setResult]=useState<AnyData|null>(null),[profiles,setProfiles]=useState<any[]>([]),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<AnyData|null>(null);
 useEffect(()=>{fetch(API+'/api/config').then(r=>r.json()).then(setConfig);fetch(API+'/api/profiles?limit=12').then(r=>r.json()).then(x=>setProfiles(x.items))},[]);
 async function run(){setBusy(true);setReceipt(null);const r=await fetch(API+'/api/workflows',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({brief,scenario})});setResult(await r.json());setBusy(false)}
 async function activate(){if(!result)return;const r=await fetch(API+'/api/activate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workflow_id:result.workflow_id,idempotency_key:'demo-'+result.workflow_id})});setReceipt(await r.json())}
 async function withdraw(){alert('Select the “Consent withdrawal after approval” scenario to deterministically revoke an approved member before activation.')}
 return <main><header><div><span className="eyebrow">IDENTITY GOVERNANCE · ADTECH</span><h1>Audience Control Room</h1></div><span className={'mode '+(config.isolated?'real':'sim')}>{config.isolated?'OPEN­SHELL ISOLATED':'⚠ SIMULATION — NOT ISOLATED'}</span></header>
 <section className="hero"><div><h2>From intent to activation,<br/><em>with authority attached.</em></h2><p>Consent-aware ranking. Narrow delegation. Immutable activation permits.</p></div><div className="decision"><small>ACTIVATION DECISION</small><strong className={(result?.decision||'WAIT').toLowerCase()}>{result?.decision||'WAITING'}</strong><span>{result?.reason||'Run a governed workflow'}</span></div></section>
 <div className="grid"><section className="card brief"><div className="title"><span>01</span><h3>Campaign brief</h3></div><label>Campaign<input value={brief.name} onChange={e=>setBrief({...brief,name:e.target.value})}/></label><label>Manager request<textarea value={brief.request} onChange={e=>setBrief({...brief,request:e.target.value})}/></label><div className="row"><label>Scenario<select value={scenario} onChange={e=>setScenario(e.target.value)}>{Object.entries(config.scenarios||{}).map(([k,v])=><option value={k} key={k}>{String(v)}</option>)}</select></label><label>Max audience<input type="number" value={brief.max_audience} onChange={e=>setBrief({...brief,max_audience:+e.target.value})}/></label></div><button onClick={run} disabled={busy}>{busy?'Coordinating…':'Run governed workflow →'}</button></section>
 <section className="card"><div className="title"><span>02</span><h3>Audience funnel</h3></div>{result?.funnel?<><div className="metrics"><b>{result.funnel.generated}<small>generated</small></b><b>{result.funnel.eligible}<small>eligible</small></b><b>{result.funnel.approved}<small>approved</small></b></div><div className="bar"><i style={{width:(result.funnel.approved/result.funnel.generated*100)+'%'}}/></div><p className="muted">Exclusions: {JSON.stringify(result.funnel.excluded)}</p></>:<p className="empty">Funnel appears after a run.</p>}<div className="actions"><button className="secondary" onClick={withdraw}>Withdraw consent</button><button onClick={activate} disabled={result?.decision!=='GO'}>Activate mock</button></div>{receipt&&<pre>{JSON.stringify(receipt,null,2)}</pre>}</section>
 <section className="card wide"><div className="title"><span>03</span><h3>Agent execution timeline</h3><i className="legend">GOVERNANCE / SANDBOX</i></div><div className="timeline">{(result?.timeline||Object.keys(config.sandboxes||{}).map(agent=>({agent,status:'idle',sandbox_id:config.sandboxes[agent],governance:'pending'}))).map((x:any,i:number)=><div className={'agent '+x.status} key={x.agent}><span>{String(i+1).padStart(2,'0')}</span><b>{x.agent}</b><code>{x.sandbox_id}</code><i>{x.governance}</i>{x.reason&&<small>{x.reason}</small>}</div>)}</div></section>
 <section className="card wide"><div className="title"><span>04</span><h3>Delegation inspector</h3></div>{result?.grants?.length?<div className="grants">{result.grants.map((g:any)=><article key={g.grant_id}><b>{g.subject}</b><code>{g.grant_id}</code><p>{g.capabilities.join(', ')} · {g.record_budget} records</p><small>{g.root_subject} → {g.parent_grant||'root'} · expires {new Date(g.expires_at).toLocaleTimeString()}</small></article>)}</div>:<p className="empty">Signed, narrowed task grants appear here. Agents cannot mint authority.</p>}</section>
 <section className="card wide"><div className="title"><span>05</span><h3>Synthetic profile explorer</h3><i className="legend">ILLUSTRATIVE DATA</i></div><table><thead><tr><th>Customer</th><th>Visits</th><th>Purchases</th><th>Recency</th><th>AOV</th><th>Eligible</th></tr></thead><tbody>{profiles.map(p=><tr key={p.customer_id}><td>{p.customer_id}</td><td>{p.visits_30d}</td><td>{p.purchases_180d}</td><td>{p.days_since_purchase}d</td><td>${p.avg_order_value}</td><td>{p.eligible?'Yes':'No'}</td></tr>)}</tbody></table></section></div>
 <footer>No ads or emails are sent · Synthetic scores do not prove incremental lift · Policy v2026-01</footer></main>
}
createRoot(document.getElementById('root')!).render(<App/>);
